services:
  backend:
    build: ./backend
    ports:
      - "8081:8000"
    volumes:
      - ./backend:/app
    environment:
      - REDIS_URL=redis://redis:6379/0
      - ELEVEN_API_KEY=
    depends_on:
      - redis
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "8001:3000"
    environment:
      - PORT=3000
      - BACKEND_URL=http://backend:8000
    depends_on:
      - backend
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    restart: unless-stopped

